[workspace]
members = [
    # libraries
    "src/lib/dice",
    "src/lib/discord",

    # binaries
    "src/bin/frajd-o-matic",
]
resolver = "3"

[workspace.dependencies]
# repo dependencies
dice = { path = "src/lib/dice" }
discord = { path = "src/lib/discord" }

# external dependencies
poise = "0.6.2"
rand = "0.10.1"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
